swagger: '2.0'
info:
  version: '1.0'
  title: "areajs"
  description: Lo scopo è calcolare l'area di un rettangolo
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: areajs.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /getArea:
    get:
      description: |
          Esegue Calcola l'area di un rettangolo dati in input:
          
          - il primo lato del rettangolo
          
          - il secondo lato del rettangolo
          
      operationId: db_interaction
      parameters:
      
        - name: side1
          in: query
          description: rappresenta il primo lato del rettangolo
          required: true
          type: string
          collectionFormat: csv
          x-example: '2'
          
          items:
            type: string
            
        - name: side2
          in: query
          description: rappresenta il secondo lato del rettangolo
          required: true
          type: string
          collectionFormat: csv
          items:
            type: string
          x-example: '3'
          
      responses:
        200:
          description: db response
          schema:
            type: string